---
title: "Resources 2024"
---

*Pathways to Open Science 2024 starts January 25th. This page will link to the content from each Community Call (e.g. agenda, video, slides) as well as resources shared by speakers and participants. We will add resources here that come up in each session.*

*Certificates will be available with the number of hours you completed in the program.*

Quicklink: [OpenscapesCommunityCalls \[ 2024-pathways \]](https://drive.google.com/drive/folders/1H4krhccewqitgE39g7VAPFQKf0aaUu82?usp=drive_link) Google Drive folder

## Community Calls

### Call 1, January 25: What is open science anyway? What can it mean for you?

([Agenda](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.v4arp372yz2n) with notes and links to resources \| [Video](https://drive.google.com/file/d/128PREjilaB7Y0jULVd7b8_VZLRPkvSPz/view?usp=drive_link))

Meet the team: [Ileana Fenwick](https://twitter.com/_ileanaf), [Aneese Williams, MSc](https://www.linkedin.com/in/aneese-williams-mps-80a846b6/), [Alex Davis, PhD](http://www.alexandracddavis.com/)

Speakers

-   [Ileana Fenwick](https://twitter.com/_ileanaf), UNC PhD Candidate, Openscapes Team member
    -   Data strategies for Future Us ([slides](https://docs.google.com/presentation/d/1LN3bMRdxZXE_4yqOBPF30mz8hAf-6gGx2v1hMHBecRc/))
-   [Aliyah Griffith](https://aliyahgg.wixsite.com/aliyah-griffith/), UNC PhD Candidate, CEO of Mahogany Mermaids, National Geographic Explorer
-   [Bárbara Pinheiro](https://www.instagram.com/barbara.pin/), Post Doctoral research fellow, [PELD CCAL- Universidade Federal de Alagoas, Maceió- Brazil](https://sites.google.com/view/peld-costa-dos-corais-al/equipe?authuser=0)(in Portuguese)

### Call 2, February 8: Building our skills for a better tomorrow

([Agenda](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.y0zhyd3y1f29) with notes and links to resources \| [Video](https://drive.google.com/file/d/1hUEs7flNMa5yd7YUha9tau-BGBSjAbS3/))

Speakers

-   [Aneese Williams, MSc](https://www.linkedin.com/in/aneese-williams-mps-80a846b6/), Environmental Management Systems (EMS) Coordinator, City of West Palm Beach
    -   My journey to open science ([slides](https://docs.google.com/presentation/d/1FFCBGvOmr1FpCaKK7JU0C5rpdv2oQ7_Q/))
-   [LaTreese Denson, PhD](https://www.bweems.org/member-directory/latreese-s-denson-ph-d), Stock Assessment Analyst, NOAA Southeast Fisheries Science Center
-   [Antoinette Foster, PhD](https://www.ohsu.edu/racial-equity-and-inclusion-center/our-people), Director of Community Transformation, OHSU

LaTreese's and Antoinette's slides can be viewed in the recording. Aneese's slides are linked above.

### Call 3, February 22: Data Science is for US

([Agenda](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.t7xxkwa7gaf4) with notes and links to resources \| [Video](https://drive.google.com/file/d/1OwFJlFr1sfSILKjZMfLJbQf838z5E7eX/))

Speakers

-   [Alex Davis, PhD](http://www.alexandracddavis.com/), Postdoctoral Fellow, aquatic invasive species ecologist, UCLA
    -   What Open Science means to me ([slides](https://docs.google.com/presentation/d/1b3oUq-jc01HyEV_eRijPyF6qYURpcB4c/edit?usp=drive_link&ouid=117331415908654768512&rtpof=true&sd=true))
-   [SherAaron Hurt](https://carpentries.org/team/), Director of Workshops, The Carpentries
    -   Journey to Open Science ([slides](https://www.canva.com/design/DAF9jeVCeTI/MR1bstUE6kgZPS8M0H2EKw))
-   [Justin Rice, PhD](https://www.nasa.gov/image-article/deputy-manager-justin-rice/), Deputy Manager of the ESDIS Science Systems Development Office, NASA's Goddard Space Flight Center
-   [Dawn Wright, PhD](https://twitter.com/deepseadawn), Chief Scientist, Environmental Systems Research Institute (ESRI)

## Coworking Sessions

Coworking comes in many flavors. For us, coworking involves doing our own work at the same time together with opportunities to check in, and sometimes screenshare to get feedback or solve a problem. Seeing how other people work is a big part of this transition to working more openly and collaboratively.

We have breakout rooms to meet the speakers, for topic-based screenshares and discussions, and for socializing or quiet working. Follow the links to our collaborative notes doc to see the resources everyone shared on R and tidy data, Python, math, GIS, data visualization, Quarto, GitHub, ocean biodiversity data, NASA TOPS Open Science 101 Modules, training and paid internships, Data that’s FAIR (Findable, Accessible, Interoperable, Reusable) and open, storymaps, replicability and reproducibility.

[February 1](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.k5xex36bbt1k) \| [February 15](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.8jo8fpfqrb5p) \| February 29

## Resources recommended by Speakers

Aliyah Griffith

-   [The Big Book of R](https://www.bigbookofr.com/)
-   [PSU R Statistical Software Tutorial](https://online.stat.psu.edu/statprogram/tutorials/statistical-software/r)
-   [Google Colab](https://colab.google/) and [example](https://colab.research.google.com/github/microsoft/torchgeo/blob/releases/v0.4/docs/tutorials/trainers.ipynb#scrollTo=b13c2251)

Bárbara Pinheiro

-   Ocean Biodiversity Information System - a global open-access data and information clearing-house on marine biodiversity for science, conservation and sustainable development
    -   <https://mapper.obis.org/>
    -   <https://github.com/iobis>
    -   <https://github.com/iobis/robis>

Ileana Fenwick

-   [Tidy data Illustrated Series](https://www.openscapes.org/blog/2020/10/12/tidy-data/)
-   Good resource for [how to start a project in R](https://njsilbiger.github.io/GettingStarted/)
-   [BioTIME](https://biotime.st-andrews.ac.uk/)

Call 1 participants recommend

-   R
    -   I use this posit package to data wrangle <https://dplyr.tidyverse.org/>
    -   [Janitor R package](https://sfirke.github.io/janitor/) for cleaning data in R
    -   The Carpentries [Intro to R](https://datacarpentry.org/R-genomics/01-intro-to-R.html)
-   Datasets from NOAA, USGS, etc. to practice data mining and visualization:
    -   This ["tidy coral" lesson](https://nceas.github.io/crescynt-training/tidy_coral) helped walk through NOAA buoy data in R
    -   The [USGS Vizlab](https://labs.waterdata.usgs.gov/visualizations/) links back to the source data and reusable code
-   GIS
    -   [Tutorials](https://learn.arcgis.com/en/projects/predict-seagrass-habitats-with-machine-learning/) from learn.arcgis.com
    -   [NOAA has also published some surveys](https://experience.arcgis.com/experience/dfe13b44993b4449bf47422db9d0e1a6/) that may be good practice from a more social science (socioeconomic) perspective
