---
title: "Resources 2025"
---

*Pathways to Open Science 2025 runs weekly January 23 to February 27, 5:00 - 6:30 pm ET. This page links to the content from each Community Call (e.g. agenda, video, slides) and the Agenda doc includes many linked resources shared by speakers and participants.*

*Certificates will be granted for anyone who participates in one or more of the six sessions.*

Quicklink: [OpenscapesCommunityCalls [ 2025-pathways ]](https://drive.google.com/drive/folders/1jwm37xpIzijJMi1PstOMJkWbIhPEAIsV?usp=drive_link) Google Drive folder

# Community Calls

## Call 1, January 23: What is open science anyway? And what can it mean for you?

<!--- [Agenda](https://docs.google.com/document/d/1ma_a2FNXQa-a3th--xWtGUbuhK3ct8g4RsaKpxncfHA/edit?usp=drive_link) with notes and links to resources | [Video] (TO COME) 
--->

**What is Openscapes?** ([slides](https://docs.google.com/presentation/d/1HSSpz6tUVGgHjJ0UIMoEd9u0h84VerjbObR5OPvCids/)), by [Ileana Fenwick](https://twitter.com/_ileanaf), UNC PhD Candidate, Openscapes Team member

**What does open science mean to me?** ([slides](https://docs.google.com/presentation/d/1RAEYTlaCGNJ8MnX2jeh2piWzr599cr5R/edit?usp=drive_link&ouid=117331415908654768512&rtpof=true&sd=true)), by [Alex Davis, PhD](http://www.alexandracddavis.com/)

**Open Science can start here.** Stories from past Pathways participants!, by Ngozi Oguguah and Deniel Novella

**Data Strategies for Future Us** ([slides](https://docs.google.com/presentation/d/1MvDZ5xspJQ3BHjJbj2YDz1J6jpRYw-NPL-AvSWG-ego/)), by [Alex Davis, PhD](http://www.alexandracddavis.com/)


## Call 2, February 6: Building our skills for a better tomorrow

<!--- ([Agenda](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.y0zhyd3y1f29) with notes and links to resources \| [Video](https://drive.google.com/file/d/1hUEs7flNMa5yd7YUha9tau-BGBSjAbS3/))

Speakers

-   [Aneese Williams, MSc](https://www.linkedin.com/in/aneese-williams-mps-80a846b6/), Environmental Management Systems (EMS) Coordinator, City of West Palm Beach
    -   My journey to open science ([slides](https://docs.google.com/presentation/d/1FFCBGvOmr1FpCaKK7JU0C5rpdv2oQ7_Q/))
    -   Open Science Key Terms ([slides](https://docs.google.com/presentation/d/16RbJ3S4njI22tBjrsjxzbl3Yjv1OVNKE/))
-   [LaTreese Denson, PhD](https://www.bweems.org/member-directory/latreese-s-denson-ph-d), Stock Assessment Analyst, NOAA Southeast Fisheries Science Center
-   [Antoinette Foster, PhD](https://www.ohsu.edu/racial-equity-and-inclusion-center/our-people), Director of Community Transformation, OHSU

LaTreese's and Antoinette's slides can be viewed in the recording. Aneese's slides are linked above.
--->

## Call 3, February 20: Data Science is for US

<!--- ([Agenda](https://docs.google.com/document/d/1rRq6UweAtBzAD1ZiemnghrvolOkqTAdNJLiDm4woa8U/edit#heading=h.t7xxkwa7gaf4) with notes and links to resources \| [Video](https://drive.google.com/file/d/1OwFJlFr1sfSILKjZMfLJbQf838z5E7eX/))

Speakers

-   [Alex Davis, PhD](http://www.alexandracddavis.com/), Postdoctoral Fellow, aquatic invasive species ecologist, UCLA
    -   What Open Science means to me ([slides](https://docs.google.com/presentation/d/1b3oUq-jc01HyEV_eRijPyF6qYURpcB4c/edit?usp=drive_link&ouid=117331415908654768512&rtpof=true&sd=true))
-   [SherAaron Hurt](https://carpentries.org/team/), Director of Workshops, The Carpentries
    -   Journey to Open Science ([slides](https://www.canva.com/design/DAF9jeVCeTI/MR1bstUE6kgZPS8M0H2EKw))
-   [Justin Rice, PhD](https://www.nasa.gov/image-article/deputy-manager-justin-rice/), Deputy Manager of the ESDIS Science Systems Development Office, NASA's Goddard Space Flight Center
-   [Dawn Wright, PhD](https://twitter.com/deepseadawn), Chief Scientist, Environmental Systems Research Institute (ESRI)
--->

# Coworking Sessions

Coworking comes in many flavors. For us, coworking involves doing our own work at the same time together with opportunities to check in, and sometimes screenshare to get feedback or solve a problem. Seeing how other people work is a big part of this transition to working more openly and collaboratively.

Coworking sessions happen January 30, 13, 27. We have breakout rooms to meet the speakers, for topic-based screenshares and discussions, and for socializing or quiet working. Follow the links in our collaborative notes doc to see the resources people share.
