project:
  type: website
  output-dir: docs

website:
  title: "Pathways to Open Science"

  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes Core Team"
 
  navbar:
    logo: images/openscapes_hex.png
    href: https://openscapes.org
    right:
      - text: "Resources"
        menu: 
            - text: "2024"
              href: 2024.qmd 
            - text: "2023"
              href: 2023.qmd
      - text: "Home"
        href: https://openscapes.org
      - icon: github
        href: https://github.com/openscapes/pathways-to-open-science
      - icon: mastodon
        href: https://fosstodon.org/@openscapes
        
format:
  html:
    theme: cosmo
    toc: true
