project:
  type: website

website:
  title: "Pathways to Open Science"

  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes Core Team"
 
  navbar:
    logo: images/openscapes_hex.png
    href: https://openscapes.org
    right:
      - text: "Pathways"
        href: index.qmd
      - text: "Home"
        href: https://openscapes.org
      - icon: github
        href: https://github.com/openscapes/events
      - icon: twitter
        href: https://twitter.com/openscapes
        
format:
  html:
    theme: cosmo
    toc: true