---
title: "Resources"
---

Quicklink: [OpenscapesCommunityCalls \[ 2023-pathways \]](https://drive.google.com/drive/folders/19AprdqWkO4SSBHD6XwzHRcPoniQm2bYy) Google Drive folder

This page links to the content from each Community Call (e.g. agenda, video, slides) as well as more general resources like [Some recommended datasets for teaching].

We will add resources here that come up in each session!

## Community Calls

### Call 01, January 26: What is open science anyway? What can it mean for you?

Learn all about open science and data organization skills that will save you time and energy!

Ileana Fenwick, Aneese Williams, and Alex Davis each shared a story of their path to open science and Ileana taught us about Data Strategies for Future Us. There were [80 participants!](https://twitter.com/curly_scientist/status/1618735555415805953)!

([Agenda](https://docs.google.com/document/d/1c9bv0YqhN0ifQEMmd8Es7L7LDx1RQCMZPPsVhkV38yc/edit#) \| [Video](https://drive.google.com/file/d/1Vt0F9RhH41Fgf5KapuD-XYUR0-gKtaAN/view) \| [Slides](https://drive.google.com/drive/folders/1PrK9-OFmR8stgI3sZPHOsUaOQi0D9FlF))

Speakers

-   [Alex Davis](http://www.alexandracddavis.com/), Postdoctoral Fellow, The Diversity Project at UCLA, and Pathways co-organizer
-   [Ileana Fenwick](https://twitter.com/_ileanaf), PhD Student, UNC Chapel Hill and Pathways Lead
-   [Aneese Williams](https://www.linkedin.com/in/aneese-williams-mps-80a846b6/), Environmental Management Systems Coordinator for the City of West Palm Beach, FL and Pathways co-organizer

## Coworking

[Collaborative notes](https://docs.google.com/document/d/1t0WXHZEiNtM6p6haEQgGJXZKC5t8Ek_m4qHa-k6Ntfo/) Google doc. Notes from 3 coworking sessions all in the same doc.

### Coworking #1

We had breakout rooms for social or quiet working, plus rooms for discussions, screenshares and learning about Datasets for Classrooms+Working/learning in R and Tools / ArcGIS.

-   **Tools/ArcGIS**

    -   <https://brooklab.org/> \> Bat lab led by Cara Brook

    -   Googling for tutorials together

        -   <https://spatialanalysis.github.io/tutorials/>

        -   <https://sites.tufts.edu/gis/learning-gis/online-tips-and-tutorials/tufts-gis-tip-sheets-arcgis10/> 

        -   <https://ohi-science.org/training/> \> Spatial Analysis \> [A primer on coordinate reference systems](https://github.com/OHI-Science/ohi-science.github.io/raw/dev/assets/downloads/other/CRS.pdf) (download, created by Melanie Frazier)

    -   R spatial software, and tutorials: <https://r-spatial.org/> 

    -   Light datasets?

        -   <https://data.neonscience.org/data-products/explore?search=light%20pollution>

        -   <https://search.earthdata.nasa.gov/search?lat=-0.0703125> \> Openscapes Slack to connect directly with LandSAT data center folks!

    -   <https://www.esri.com/arcgis-blog/author/deepseadawn/> 

```{=html}
<!-- -->
```
-   **Datasets for Classrooms / working & learning in R**

    -   R tutorials for fish and ecological data

        -   materials for the #BlackInMarineScience week intro to R workshop, \#[PuttingTheSEAInCode](https://github.com/latreesedenson/PuttingTheSEAInCode)

        -   [BWEEMS](https://www.bweems.org/) professional development workshop, [DirtyData-CleanMaps](https://github.com/OfficialBweems/DirtyData-CleanMaps)

    -   Biology Tutorials for [R](https://colebrookson.github.io/r-for-biology/) and [Python](https://colebrookson.github.io/python-for-biology/), by Cole Brookson

    -   Camille\'s dataset, [FishScapes/hyperstabilitySurvey](https://zenodo.org/record/6944763#.Y9w5nnbMK3A)

## Some recommended datasets for teaching {data-link="Some recommended datasets for teaching"}

-   Palmer Archipelago Penguins Data in the palmerpenguins R Package ([paper](https://journal.r-project.org/articles/RJ-2022-020/), [talk](https://allisonhorst.github.io/talks/sb_users_penguins_flash/), [useR! 2022 talk](https://apreshill.github.io/palmerpenguins-useR-2022/#/title-slide))

-   lterdatasampler ([talk](https://allisonhorst.github.io/talks/esa_2021/) Leveraging data richness of the Long Term Ecological Research Network for an R datasets package)

-   [TidyTuesday](https://github.com/rfordatascience/tidytuesday), A weekly social data project in R. Datasets include [Tuskegee Airmen](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-02-08/readme.md#tuskegee-airmen) and [Juneteenth](https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-06-21)

-   Elevated blood lead level test results for St. Louis, MO (great [repository](https://github.com/slu-soc1120/STL_HEALTH_Lead) with R code examples, links to articles about it, etc, from Chris Prener)

-   [CalEnviroScreen](https://oehha.ca.gov/calenviroscreen) and [EJscreen](https://www.epa.gov/ejscreen) have lots to explore and investigate. The data are in pretty nice shape already; can be joined with other data (e.g. census).

-   For global datasets go to [WorldBank](https://data.worldbank.org/) (to make the data tidy, you have to use both a `pivot_longer` and a `pivot_wider`; these are functions in [tidyr](https://tidyr.tidyverse.org/) R package)

-   USDA [Food Access Research Atlas](https://www.ers.usda.gov/data-products/food-access-research-atlas/) (food access; food deserts).

-   This [Twitter thread](https://twitter.com/k_lyberger/status/1344733416017645569) has good suggestions for social justice & some environmental justice-related datasets.

-   The [Open Case Studies project](https://www.opencasestudies.org/) is an educational resource of experiential guides that demonstrate how to effectively derive knowledge from data in real-world challenges. ([preprint](https://arxiv.org/abs/2301.05298), [Educator's Guide](https://www.opencasestudies.org/OCS_Guide/), Twitter [thread](https://twitter.com/stephaniehicks/status/1615322767380910081))
